const displayLabels: Record<string, string> = {
  ACTIVE: "活跃",
  ARCHIVED: "已归档",
  CANCELLED: "已取消",
  CHECKING: "检查中",
  CLOSED: "已关闭",
  CLOSING: "关闭中",
  DEGRADED: "部分可用",
  DELIVERED: "已送达",
  DISABLED: "已停用",
  DISPATCHED: "已下发",
  DISPATCH_FAILED: "任务派发失败",
  DISPATCHING: "任务派发中",
  DOWN: "异常",
  DRAFT: "草稿",
  EPHEMERAL: "临时模式",
  EXPIRED: "已过期",
  FAILED: "失败",
  FAIL_FAST: "立即失败",
  HEALTHY: "健康",
  HUMAN_CONTROL: "人工接管中",
  INCONCLUSIVE: "结果不确定",
  INFO: "信息",
  INTEGRATION_ERROR: "集成异常",
  LOST: "已失联",
  NOT_READY: "未就绪",
  OFFLINE: "离线",
  ONLINE: "在线",
  OPENING: "启动中",
  PASSED: "已通过",
  PENDING: "等待中",
  PERSISTENT: "持久模式",
  PROCESSING: "处理中",
  QUEUED: "排队中",
  READY: "就绪",
  RESOLVED: "已处理",
  REVOKED: "已撤销",
  RUNNING: "运行中",
  SETUP_REQUIRED: "待配置",
  SKIPPED: "已跳过",
  STALE: "长时间未更新",
  STARTED: "已开始",
  SUCCEEDED: "成功",
  SUSPENDED: "已停用",
  TIMED_OUT: "已超时",
  UP: "正常",
  WAIT: "等待",
  WAITING_CAPACITY: "等待执行槽位",
  WAITING_EXECUTION: "等待执行环境",
  WAITING_HUMAN: "等待人工操作",
  WAITING_INPUT: "等待输入",
  WAITING_DEPLOYMENT: "等待部署地址",
  DEPLOYMENT_TARGET_REQUIRED: "等待部署地址",
  LINKED: "已关联 Run",
  ISSUE_SPEC: "Issue 任务",
  DIRECT_RUN: "直接任务",
  LEGACY_RUN: "历史任务",
  SPEC_ANALYSIS: "Spec 分析生成",
  SPEC_EXECUTION: "Spec 执行",
  TASK_CASE: "任务 Case",
  SPEC_CASE: "Spec Case",
  PLAYGROUND: "试验场",
  PREPARING: "准备中",
  COMPLETED: "已完成",
  EXECUTED: "已执行",
  NOT_RUN: "未执行",
  BLOCKED: "被阻塞",
  AGENT_ERROR: "Agent 异常",
  PROVIDER_ERROR: "模型服务异常",
  BROWSER_UNAVAILABLE: "浏览器不可用",
  RUNTIME_LOST: "执行节点失联",
  RELEASED: "已释放",
  CODEX: "Codex Agent",

  AGENT: "Agent",
  BROWSER: "浏览器",
  CONSOLE: "控制台",
  HUMAN: "人工",
  RUNNER: "执行节点",
  SYSTEM: "系统",
  WORKER: "后台任务",

  SCREENSHOT: "截图",
  DOM: "页面结构",
  NETWORK: "网络记录",
  BUSINESS_REFERENCE: "业务来源",
  NO_AVAILABLE_SLOT: "暂无可用执行槽位",
  NO_MATCHING_RUNNER: "无匹配执行节点",
  UNAVAILABLE: "不可用",

  verificationStatuses: "验证任务",
  taskStatuses: "任务执行",
  taskStageStatuses: "任务阶段",
  commandStatuses: "执行命令",
  outboxStatuses: "通知投递",
  runtimes: "执行节点",

  database: "数据库",
  objectStorage: "对象存储",
  redis: "Redis",
  "execution-wait-sweeper": "执行等待清理任务",
  "hitl-expiry": "人工接管过期清理任务",
  "notification-outbox": "通知投递任务",
  "specification-execution": "Spec 任务派发",
  "task-execution": "任务执行编排",
  retention: "数据保留清理任务",
  "tool-invocation-sweeper": "工具调用清理任务",
  "verification-cleanup": "验证任务清理任务",

  "assertion.recorded": "已记录验收结论",
  "agent.model.completed": "模型调用已完成",
  "agent.model.failed": "模型调用失败",
  "agent.progress": "Agent 进度更新",
  "agent.runtime.completed": "Agent Runtime 已完成",
  "agent.runtime.failed": "Agent Runtime 运行失败",
  "agent.runtime.paused": "Agent Runtime 已暂停",
  "agent.runtime.resumed": "Agent Runtime 已恢复",
  "agent.runtime.started": "Agent Runtime 已启动",
  "agent.tool.completed": "Agent 工具调用已完成",
  "agent.tool.failed": "Agent 工具调用失败",
  "execution.acquire.failed": "获取执行环境失败",
  "execution.acquired": "已获取执行环境",
  "execution.command.completed": "执行命令已完成",
  "execution.command.failed": "执行命令失败",
  "execution.command.started": "执行命令已开始",
  "execution.lost": "执行环境已失联",
  "execution.queue.full": "执行队列已满",
  "execution.released": "执行环境已释放",
  "execution.waiting": "正在等待执行环境",
  "browser.execution.waiting_capacity": "正在等待浏览器执行槽位",
  "hitl.expired": "人工检查点已过期",
  "hitl.requested": "已请求人工操作",
  "hitl.resolved": "人工检查点已处理",
  "notification.delivered": "通知已送达",
  "notification.enqueued": "通知已加入队列",
  "notification.failed": "通知发送失败",
  console_error: "浏览器控制台错误",
  human_input: "人工输入",
  network_error: "网络错误",
  network_fault_hit: "已触发网络故障规则",
  page_changed: "页面已变化",
  session_interrupted: "浏览器会话已中断",
  "verification.cancelled": "验证已取消",
  "verification.completed": "验证已完成",
  "verification.created": "验证已创建",
  "verification.started": "验证已开始",
  "verification.timed_out": "验证已超时",
  "run.queued": "任务已排队",
  "run.retry.queued": "任务已进入重试",
  "run.cancelled": "任务已取消",
  "run.timed_out": "任务已超时",
  "task.created": "任务已创建",
  "task.stage.started": "任务阶段已开始",
  "task.stage.succeeded": "任务阶段已完成",
  "task.stage.failed": "任务阶段失败",
  "task.stage.retry_queued": "任务阶段已进入重试",
  "task.waiting_input": "任务等待输入",
  "task.input.provided": "任务输入已提供",
  "task.case.run_created": "Case 执行已创建",
  "task.case.dispatch_failed": "Case 派发失败",
  "task.cancel_requested": "任务已请求取消",
  "task.completed": "任务已完成",
  "task.migrated": "历史任务已迁移",
  "task.rerun.created": "已创建重跑任务",
  "task.rerun.linked": "已关联原任务",
  MIGRATION: "数据迁移",
  "runtime.task.claimed": "Agent Runtime 已领取任务",
  "runtime.outcome.verification_completed": "验证执行已完成",
  "runtime.outcome.retryable_failure": "发生可重试异常",
  "runtime.outcome.fatal_failure": "发生终止异常",
  "runtime.outcome.waiting_human": "等待人工操作",
  "browser.execution.acquired": "已获取浏览器执行环境",
  "browser.execution.released": "已释放浏览器执行环境",
  "browser.command.started": "浏览器命令已开始",
  "browser.command.completed": "浏览器命令已完成",
  "human.intervention.resolved": "人工操作已处理",

  "human.release": "释放人工控制",
  "human.takeover": "开始人工接管",
  "page.navigate": "打开页面",
  "page.snapshot": "采集页面快照",
  "session.close": "关闭浏览器会话",
  "session.open": "打开浏览器会话",

  browser_runtime: "浏览器执行节点",
  browser_runtime_pairing_token: "执行节点配对凭证",
  browser_runtime_session: "浏览器会话",
  runtime_routing_rule: "执行节点路由规则",
  runtime_settings: "执行节点设置",
  test_case: "测试用例",
  test_case_version: "测试用例版本",
  test_environment: "测试环境",
  test_project: "测试项目",
  test_run: "测试任务",
  test_run_human_checkpoint: "测试任务人工检查点",
  tool_credential: "工具凭证",
  "runtime.pairing_token.created": "已创建执行节点配对凭证",
  "runtime.network_policy.updated": "已更新执行节点网络白名单",
  "runtime.configuration.updated": "已更新执行节点访问与容量配置",
  "runtime.revoked": "已撤销执行节点",
  "runtime.routing_rule.created": "已创建执行节点路由规则",
  "runtime.routing_rule.deleted": "已删除执行节点路由规则",
  "runtime.routing_rule.updated": "已更新执行节点路由规则",
  "runtime.session.closed": "已关闭执行节点会话",
  "runtime.session.created": "已创建执行节点会话",
  "runtime.session.human_control.released": "已释放人工控制",
  "runtime.session.human_control.started": "已开始人工接管",
  "runtime.settings.updated": "已更新执行节点设置",
  "test.case.created": "已创建测试用例",
  "test.case.updated": "已更新测试用例",
  "test.case.version.created": "已创建测试用例版本",
  "test.environment.created": "已创建测试环境",
  "test.environment.updated": "已更新测试环境",
  "test.project.created": "已创建测试项目",
  "test.project.updated": "已更新测试项目",
  "test.run.checkpoint.resolved": "已处理测试任务人工检查点",
  "test.run.queued": "测试任务已加入队列",
  "tool.credential.created": "已创建工具凭证",
  "tool.credential.revoked": "已撤销工具凭证",
};

export function displayLabel(value: string | null | undefined): string {
  if (!value) return "—";
  return displayLabels[value] ?? value;
}

const messageTranslations: Record<string, string> = {
  "A routing rule already exists for this hostname pattern.":
    "该域名规则已存在。",
  "A tool credential with this name already exists.": "同名工具凭证已存在。",
  "A valid DevProof tool token is required.":
    "需要有效的 DevProof 工具 Token。",
  "Browser control is no longer active.": "浏览器人工控制已结束。",
  "Browser control lease has expired.": "浏览器人工控制已过期。",
  "Browser input rate limit exceeded.": "浏览器输入过于频繁，请稍后重试。",
  "Browser Runtime must be restarted with human input protocol support.":
    "请重启浏览器执行节点并启用人工输入协议支持。",
  "Browser Runtime must be restarted with preview protocol support.":
    "请重启浏览器执行节点并启用实时预览协议支持。",
  "Browser Runtime rejected control release.":
    "浏览器执行节点未能释放人工控制。",
  "Browser Runtime rejected human control.": "浏览器执行节点未能开始人工控制。",
  "Browser Runtime has no available slot.": "浏览器执行节点暂无可用执行槽位。",
  "Browser Runtime is offline.": "浏览器执行节点已离线。",
  "Browser Runtime session is not available.": "浏览器执行节点会话不可用。",
  "Browser Runtime was not found.": "未找到浏览器执行节点。",
  "Checkpoint has expired.": "人工检查点已过期。",
  "Execution queue admission conflicted.": "加入执行队列时发生冲突。",
  "HITL checkpoint is no longer pending.": "人工检查点已不再等待处理。",
  "HITL checkpoint was not found.": "未找到人工检查点。",
  "Human control is disabled for this team.": "当前团队未启用人工接管。",
  "Mutation origin is not allowed.": "当前请求来源无权执行修改操作。",
  "Only an active session can be taken over.": "只能接管活跃的浏览器会话。",
  "Only the current human controller can release this session.":
    "只有当前接管人可以释放该会话。",
  "Only the requester can select requester profile mode.":
    "只有任务请求人可以选择“使用我的浏览器身份”；你可以改为指定自己的浏览器身份，或选择临时会话。",
  "Pairing token was already claimed.": "配对 Token 已被使用。",
  "Runtime command was not found.": "未找到执行节点命令。",
  "Runtime routing rule was not found.": "未找到执行节点路由规则。",
  "Runtime session is already controlled.": "执行节点会话已被其他窗口接管。",
  "Runtime session is not active.": "执行节点会话当前未处于活跃状态。",
  "Runtime session was not found.": "未找到执行节点会话。",
  "Selected Runtime is unavailable.": "所选执行节点不可用。",
  "Session is invalid or expired.": "登录状态无效或已过期。",
  "Sign in with Feishu.": "请使用飞书登录。",
  "This browser handoff is already controlled in another window.":
    "该浏览器接管任务已在其他窗口中操作。",
  "This browser session is controlled by another user.":
    "该浏览器会话正由其他用户控制。",
  "This checkpoint is not attached to a Browser Runtime session.":
    "该检查点未关联浏览器执行节点会话。",
  "Tool credential is invalid or expired.": "工具凭证无效或已过期。",
  "Tool credential expiry must be in the future.":
    "工具凭证的过期时间必须晚于当前时间。",
  "Tool credential requires verification:read and verification:write scopes.":
    "工具凭证需要 verification:read 和 verification:write 权限。",
  "Tool credential was not found or is revoked.":
    "未找到工具凭证，或凭证已被撤销。",
  "Verification artifact was not found.": "未找到验证制品。",
  "Verification is not waiting for human input.":
    "验证任务当前不在等待人工操作。",
  "Verification run changed concurrently.":
    "验证任务已被其他操作更新，请重试。",
  "Verification run was not found.": "未找到验证任务。",
};

export function displayMessage(value: string | null | undefined): string {
  if (!value) return "";
  if (messageTranslations[value]) return messageTranslations[value];
  if (value.startsWith("Tool credential is invalid or expired.")) {
    return `工具凭证无效或已过期。${value.slice(38)}`;
  }
  return value;
}
