#!/usr/bin/env bash

set -Eeuo pipefail

readonly RELEASE_REPOSITORY="ethanyu-dev/devproof"
readonly PACKAGE_ASSET="devproof-browser-runtime.tgz"
readonly INSTALLER_ASSET="install-browser-runtime.sh"
readonly CHECKSUM_ASSET="SHA256SUMS"

VERSION=""
FORCE_ACTIVE=false

usage() {
  cat <<'EOF'
Download, verify, and install or upgrade DevProof Browser Runtime on Linux.

Usage:
  curl -4 -fsSL https://github.com/ethanyu-dev/devproof/releases/latest/download/install.sh | bash

Options:
  --version VERSION     Install a specific runtime-vVERSION release.
  --force-active        Continue when persisted browser sessions are active.
  -h, --help            Show this help.

An unpaired first installation leaves the service ready but stopped. Run the
pairing command generated by Console to register and start it. Later upgrades
use the same curl command and preserve the existing Runtime state.
EOF
}

die() {
  printf 'error: %s\n' "$*" >&2
  exit 1
}

while (($#)); do
  case "$1" in
    --version)
      (($# >= 2)) || die "--version requires a value."
      VERSION="$2"
      shift 2
      ;;
    --force-active)
      FORCE_ACTIVE=true
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *) die "unknown argument: $1" ;;
  esac
done

[[ "$(uname -s)" == Linux ]] || die "this installer supports Linux only."
[[ -z "$VERSION" || "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] ||
  die "--version must use MAJOR.MINOR.PATCH format."
command -v curl >/dev/null || die "curl is required."
command -v sha256sum >/dev/null || die "sha256sum is required."

release_base="https://github.com/$RELEASE_REPOSITORY/releases"
if [[ -n "$VERSION" ]]; then
  release_base="$release_base/download/runtime-v$VERSION"
else
  release_base="$release_base/latest/download"
fi

mkdir -p "$HOME/.cache"
temporary="$(mktemp -d "$HOME/.cache/devproof-runtime-release.XXXXXX")"
cleanup() {
  rm -rf -- "$temporary"
}
trap cleanup EXIT
trap 'exit 129' HUP
trap 'exit 130' INT
trap 'exit 143' TERM

download() {
  local asset="$1"
  printf 'Downloading %s...\n' "$asset"
  curl --ipv4 --fail --location --silent --show-error \
    --output "$temporary/$asset" "$release_base/$asset"
}

download "$CHECKSUM_ASSET"
download "$INSTALLER_ASSET"
download "$PACKAGE_ASSET"

checksum_for() {
  local asset="$1"
  awk -v asset="$asset" '
    $1 ~ /^[[:xdigit:]]{64}$/ && ($2 == asset || $2 == "*" asset) {
      print $1
      exit
    }
  ' "$temporary/$CHECKSUM_ASSET"
}

installer_sha256="$(checksum_for "$INSTALLER_ASSET")"
package_sha256="$(checksum_for "$PACKAGE_ASSET")"
[[ -n "$installer_sha256" ]] ||
  die "$CHECKSUM_ASSET does not contain $INSTALLER_ASSET."
[[ -n "$package_sha256" ]] ||
  die "$CHECKSUM_ASSET does not contain $PACKAGE_ASSET."
printf '%s  %s\n' "$installer_sha256" "$temporary/$INSTALLER_ASSET" |
  sha256sum --check --status || die "$INSTALLER_ASSET checksum mismatch."
printf '%s  %s\n' "$package_sha256" "$temporary/$PACKAGE_ASSET" |
  sha256sum --check --status || die "$PACKAGE_ASSET checksum mismatch."
chmod 0700 "$temporary/$INSTALLER_ASSET"

installer_args=(
  --package "$temporary/$PACKAGE_ASSET"
  --sha256 "$package_sha256"
)
[[ "$FORCE_ACTIVE" == true ]] && installer_args+=(--force-active)
"$temporary/$INSTALLER_ASSET" "${installer_args[@]}"

trap - EXIT HUP INT TERM
cleanup
